### PR TITLE
De-linting

### PR DESCRIPTION
**Pull request by oblivia-simplex**
Did a fair bit of de-linting, so that the project now passes `cargo clippy --all`.

### CODE REVIEW

**Comment by emmanuel099** [comment]
Thanks for your PR!

Most of your PR looks good already.
Can you please fix the compilation errors? See https://travis-ci.org/github/falconre/falcon/builds/702122692

**Comment by oblivia-simplex** [comment]
Ah, that must be the result of me listening to clippy and deleting a bunch
of "unnecessary" `into()`s! I didn't see these errors when building with
the capstone4 feature enabled, so I guess they must be capstone3 specific.
I'm unfortunately unable to compile the capstone3 version on my system, as
it stands, but I could try to set up a VM or docker container to do so.

**Comment by endeav0r** [comment]
It may be time to drop capstone 3 support...

**Comment by oblivia-simplex** [comment]
Have you thought of switching over to the `capstone` crate? Or are there
features in falcon_capstone that aren't replicated there?

**Comment by endeav0r** [comment]
If you’re talking about the crate where m4b is a maintainer, that crate postdates Falcon. We could switch, and I’m not against it, but it would take a lot of work and modifications to the lifters.

**Comment by endeav0r** [comment]
I haven't forgotten this. My plan is to merge this over the weekend, break the build, and then fix it.

**Pull request merged**
