### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by endeav0r**
@emmanuel099 This adds an option to translators, allowing all unhandled instructions to be lifted to intrinsics. This is also an API-breaking change, so 0.5.0 bump.

Anything you want to throw in/change that may be API breaking?

### CODE REVIEW

**Comment by emmanuel099** [comment]
1. Make use of rustc-hash in Graph which brings some nice performance gains for large CFGs (esp. after loop unrolling and function inlining) (https://github.com/emmanuel099/falcon/commit/585a5a9a729b289274387c8e473f377672f15c23)
1. Placeholder in `nop` would be great (https://github.com/falconre/falcon/issues/71) 
1. Conditional operation would be awesome (https://github.com/falconre/falcon/issues/71) 

When 2. and 3. are in place I can finally get rid of all my ugly downstream hacks (https://github.com/emmanuel099/falcon/commit/4cac5d2d6939eb252323ab532ce4538cc11e6d3d and https://github.com/emmanuel099/falcon/commit/3842c0aeb81f998eeb9905bfca14a60bbe994731) :)

If 2. and 3. are OK with you, I'll try to implement one/both of them.

**Comment by endeav0r** [comment]
Yeah, let’s start hacking things up, and merge them into this PR?

**Comment by emmanuel099** [comment]
> @emmanuel099 This adds an option to translators, allowing all unhandled instructions to be lifted to intrinsics. 

Thanks, really nice change :) 
Shall we add this option to `program_recursive_verbose` and friends as well?

**Comment by emmanuel099** [comment]
@endeav0r Sorry. Unintentionally pushed my forked master to upstream master, instead of the correct branch :/ Fixed now.

FYI this PR is not merged.

**Comment by endeav0r** [comment]
lol

**Pull request merged**
