### PR TITLE
Remove docker network dependency

### PR DESCRIPTION
**Pull request by anon8675309**
Building off my previous pull request, and following the intent of making it easier for people to get started with Falcon, I've added a docker.sh script which will get the dependencies needed for Docker, install Docker, then build and run the container.

Because Docker doesn't seem to have networking available to the containers by default, I modified the Dockerfile.stretch to no longer attempt to reach out to the internet.  Instead, the llvm snapshot key is downloaded on the host (in docker.sh) and Dockerfile.stretch just copies it into the container.

In testing this, I also found that the dependencies.sh was not compatible with Debian (which doesn't have sudo installed by default), so I also updated that script as well as setup.sh.  The dependencies.sh script isn't run automatically, but the first thing I did when I went into the container was to run that so I would have everything I needed to run `cargo build`.

### CODE REVIEW

**Comment by endeav0r** [comment]
I see the amazing number of PRs. I will set time aside this weekend to get to them.

**Comment by endeav0r** [comment]
Getting around to merging things... This now conflicts :(

**Comment by anon8675309** [comment]
Verified to work as expected on Stretch, in a Docker container.  Exact commands:
- sudo ./docker.sh
- sudo docker exec -it 3bcf31ffe5e9 /bin/bash
- ./dependencies.sh  # run from within docker
- source $HOME/.cargo/env  # run from within docker
- cargo build  # run from within docker
- cd falcontest  # run from within docker
- cargo build  # run from within docker
- cargo run  # run from within docker

Also verified to work on Stretch without Docker.  Exact commands:
- sudo ./dependencies.sh
- source $HOME/.cargo/env
- cargo build
- cd falcontest
- cargo build
- cargo run

**Comment by anon8675309** [comment]
I went ahead and added support for Buster as well at Stretch.  Verified both work using vagrant (and the CI tests pass, which means there weren't any regressions in Docker).

- git clone https://github.com/anon8675309/falcon
- cd falcon
- git checkout remove_docker_network_dependency
- vagrant up  # optionally editing Vagrantfile first to change from debian9 (Stretch) to debian10 (Buster)

**Comment by endeav0r** [comment]
I'm bringing these in because I want to clear up the MRs. Thank you for this as well btw. Please don't be surprised if all these top-level scripts get moved into a subdirectory to organize a bit.

**Pull request merged**
